name: test

on:
  push:
      branches:
      - master
      paths:
      - '**'
      - '.github/workflows/linux-test.yml'
  pull_request:
      branches:
      - master
      paths:
      - '**'
      - '.github/workflows/linux-test.yml'
  workflow_dispatch:
  
jobs:
  test-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt update -y
        sudo apt install -y ninja-build gcc-11 g++-11

    - name: configure
      run: |
        mkdir build
        cd build
        export CC=/usr/bin/gcc-11
        export CXX=/usr/bin/g++-11
        cmake -GNinja ..

    - name: build
      run: |
        cd build
        cmake --build .
